paths:
  project: .
  package: C:/Users/Tiana/Code/mine/boilercore/src/boilercore
  data: data
  stages:
    modelfun: C:/Users/Tiana/Code/mine/boilercore/src/boilercore/stages/modelfun.ipynb
  fit: C:/Users/Tiana/Code/mine/boilercore/src/boilercore/models/fit.py
  model: data/model.dillpickle
